export const reducerTypes = {
  GET_USER: "reducer/GET_USER",
  GET_ALL_USERS: "reducer/GET_ALL_USERS",
  GET_CITIES: "reducer/GET_CITIES",
  GET_BASES: "reducer/GET_BASES",
  GET_BASES_RU: "reducer/GET_BASES_RU",
  GET_BASES_KZ: "reducer/GET_BASES_KZ",
  GET_LOGS_CITIES: "reducer/GET_LOGS_CITIES",
  GET_LOGS_BASES: "reducer/GET_LOGS_BASES",
  GET_COUNTRY_FOR_CHECK: "reducer/GET_COUNTRY_FOR_CHECK",
  GET_SELECTED_LANG: "reducer/GET_SELECTED_LANG",
  GET_SELECTED_LOCALE: "reducer/GET_SELECTED_LOCALE",
  GET_SPEAKER_TEMPLATES: "reducer/GET_SPEAKER_TEMPLATES",
  GET_TRAILS: "reducer/GET_TRAILS",
  GET_PLANNING_PEOPLE: "reducer/GET_PLANNING_PEOPLE",
};

export const sagaTypes = {
  GET_USER: "saga/GET_USER",
};
