export interface IForm {
  id: number;
  local: string;
  address: string;
  telephone: string[];
  email: string;
  town: string;
  voivodeship: string;
  county: string;
  day: string[];
  cost: string[];
  from: string[];
  to: string;
  payment_method: string;
  presentation_number: string[];
  confirm: string;
  presentation_time: string[];
  room_number: string[];
  parking: string;
  comments: string;
  booker: string;
  starting_price: string[];
  trade_group: string;
  company: string;
  relevanceStatus: boolean;
  city_id: number;
  region_id: number | null;
  city_name: string | null;
  region_name: string | null;
  start_coord: number | null;
  end_coord: number | null;
  createdAt: string | null;
  updatedAt: string | null;
}
